#!/usr/bin/env bash
set -u
fs=""
script=""
file=""
vars=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    -F) fs="$2"; shift 2;;
    -F*) fs="${1#-F}"; shift;;
    -v) vars+=("$2"); shift 2;;
    *) if [[ -z "$script" ]]; then script="$1"; elif [[ -z "$file" ]]; then file="$1"; else file="$1"; fi; shift;;
  esac
Done
